include ../src/config.win

BINDIR=..\bin
ASSEMBLY=LuaInterface.dll
TEST=TestLua.exe
EX=CallLua.exe

all:  $(ASSEMBLY) $(TEST) $(EX) run

$(TEST):  TestLua.cs Entity.cs
	$(CSC) -r:$(ASSEMBLY) $^

$(EX):  CallLua.cs
	$(CSC) -r:$(ASSEMBLY) $^

$(ASSEMBLY): $(BINDIR)\$(ASSEMBLY)
	copy $<
	copy $(BINDIR)\luanet.dll

run:	$(TEST)
	$(EX)
	$(TEST)

clean:
	del $(ASSEMBLY) $(TEST) $(EX) luanet.dll




